Vizsga/MindigFenyes/MindigFenyesWebModul/Models/ErrorViewModel.cs
namespace MindigFenyesWebModul.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Vizsga/MindigFenyes/MindigFenyesWebModul/Models/HibaBejelentes.cs
using System.ComponentModel.DataAnnotations.Schema;
using System.Numerics;

namespace MindigFenyesWebModul.Models
{
    public class HibaBejelentes
    {
        public string? Cim { get; set; }
        public DateTime BejelentesIdeje { get; set; }
    }
}

Vizsga/MindigFenyes/MindigFenyesWebModul/Controllers/HibaBejelentesController.cs
using Microsoft.AspNetCore.Mvc;
using MindigFenyesWebModul.Models;

namespace MindigFenyesWebModul.Controllers
{
    public class HibaBejelentesController : Controller
    {
        public IActionResult Index()
        {
            HibaBejelentes hibaBejelentes = new HibaBejelentes();
            
            return View("Index");
        }

        [HttpPost]
        public IActionResult SikeresBejelentes() 
        {
            Bejelenteseim bejelenteseim= new Bejelenteseim();
            Bejelentesek bejelentes= new Bejelentesek();
            bejelentes.Cim = Request.Form["Cim"];
            bejelentes.Idopont = new DateTime(new Random().Next(2020, 2023), new Random().Next(1,12), new Random().Next(1, 29));
            bejelenteseim.Bejelenteseks.Add(bejelentes);
            bejelenteseim.SaveChanges();

            return View();
        }
    }
}

Vizsga/MindigFenyes/MindigFenyesWebModul/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using MindigFenyesWebModul.Models;
using System.Diagnostics;

namespace MindigFenyesWebModul.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Vizsga/MindigFenyes/MindigFenyesWebModul/Views/HibaBejelentes/Index.cshtml
@model HibaBejelentes

Üdvözöllek a Mindig Fényes Kft hibabejelentő oldalán!
<br />
Bejelentéshez add meg kérlek a meghibásodás címét, és nyomd meg a "Beküldés" gombot!
<br />
<br />
A meghibásodás címének tartalmaznia kell a következőket:
<ul>
    <li>Irányítószám</li>
    <li>Helység</li>
    <li>Közterület neve</li>
    <li>Közterület jellege</li>
</ul>

<br />

Meghibásodás címe:
@using (Html.BeginForm("SikeresBejelentes", "HibaBejelentes", FormMethod.Post))
{

    @Html.TextBoxFor(m=>m.Cim, new {id ="cimed", style="width:500px;", @required = "required", @oninvalid = "this.setCustomValidity('Kérem adja meg a címet!')", @oninput="setCustomValidity('')"});
    <br />
    <br />
    <input type="submit" value="Beküldés" />
}

Vizsga/MindigFenyes/MindigFenyesWebModul/Views/HibaBejelentes/SikeresBejelentes.cshtml
@model HibaBejelentes

Sikeres hibabejelentés!

Vizsga/MindigFenyes/MindigFenyesWebModul/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Üdvözöllek a Mindig Fényes Kft. weboldalán!</h1>
    <br/>
    <h3>Hibabejelentéshez kérlek keresd fel a menüsoron a "Hiba bejelentése" opciót!</h3>
</div>

Vizsga/MindigFenyes/MindigFenyesWebModul/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MindigFenyesWebModul</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MindigFenyesWebModul.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Kezdőlap</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="HibaBejelentes" asp-action="Index">Hiba bejelentése</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Mindig Fényes Kft. Weboldala - Készítette: Serák Gábor
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>